// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsyR0-kdKYH3161IhjoKnatsqGtPF8vNI',
    appId: '1:327249087442:android:7afeeb68c633f221d6d60b',
    messagingSenderId: '327249087442',
    projectId: 'skyelive-15557',
    storageBucket: 'skyelive-15557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNBsex-pphvmGXiWxAqj8tsGYcD9WocOs',
    appId: '1:327249087442:ios:80f10447b47e1bced6d60b',
    messagingSenderId: '327249087442',
    projectId: 'skyelive-15557',
    storageBucket: 'skyelive-15557.firebasestorage.app',
    androidClientId: '327249087442-svr8505413i8c5krssbcq39q81tvghqb.apps.googleusercontent.com',
    iosClientId: '327249087442-jaskbd12084419aspak5hs00ct0r5m87.apps.googleusercontent.com',
    iosBundleId: 'com.skylive.bd.saver',
  );

}